// A Component
const heading = document.createElement("h2");
heading.textContent = "This text generated by External JavaScript";
heading.className = "header"
document.getElementById("root").append(heading);

// Another component
const head_tow = document.createElement("h1");
head_tow.textContent = "This is another component";
head_tow.className = "head_two"
document.getElementById("child").append(head_tow);